from datetime import datetime, timezone
from uuid import uuid4

from lnbits.core.db import db
from lnbits.core.models import ArkadeAccountBinding
from lnbits.db import Connection
from lnbits.settings import settings


async def create_arkade_binding(
    account_id: str, conn: Connection | None = None
) -> ArkadeAccountBinding:
    now = datetime.now(timezone.utc)
    from lnbits.core.helpers import get_arkade_configuration

    network, server_url, server_pubkey = get_arkade_configuration()
    binding = ArkadeAccountBinding(
        account_id=account_id,
        enrollment_id=uuid4().hex,
        idempotency_key=None,
        network=network,
        server_url=server_url,
        server_pubkey=server_pubkey,
        created_at=now,
        updated_at=now,
    )
    await (conn or db).insert("arkade_account_bindings", binding)
    return binding


async def get_arkade_binding(
    account_id: str, conn: Connection | None = None
) -> ArkadeAccountBinding | None:
    return await (conn or db).fetchone(
        "SELECT * FROM arkade_account_bindings WHERE account_id = :account_id",
        {"account_id": account_id},
        ArkadeAccountBinding,
    )


async def update_arkade_challenge(
    binding: ArkadeAccountBinding,
    *,
    enrollment_id: str,
    idempotency_key: str,
    nonce: str,
    expires_at: datetime,
    old_idempotency_key: str | None,
    old_nonce: str | None,
    old_expires_at: datetime | None,
    conn: Connection | None = None,
) -> bool:
    database = conn or db
    updated_at = datetime.now(timezone.utc)
    old_key_clause = (
        "idempotency_key IS NULL"
        if old_idempotency_key is None
        else "idempotency_key = :old_idempotency_key"
    )
    old_nonce_clause = (
        "challenge_nonce IS NULL"
        if old_nonce is None
        else "challenge_nonce = :old_nonce"
    )
    old_expiry_clause = (
        "challenge_expires_at IS NULL"
        if old_expires_at is None
        else (
            "challenge_expires_at = "
            f"{database.timestamp_placeholder('old_expires_at')}"
        )
    )
    result = await database.execute(
        # Timestamp placeholders are generated by the trusted DB adapter.
        f"""
        UPDATE arkade_account_bindings SET
            enrollment_id = :enrollment_id,
            idempotency_key = :idempotency_key,
            challenge_nonce = :challenge_nonce,
            challenge_expires_at = {database.timestamp_placeholder('expires_at')},
            updated_at = {database.timestamp_placeholder('updated_at')}
        WHERE account_id = :account_id AND state = 'pending'
          AND enrollment_id = :old_enrollment_id
          AND {old_key_clause}
          AND {old_nonce_clause}
          AND {old_expiry_clause}
        """,  # noqa: S608
        {
            "account_id": binding.account_id,
            "old_enrollment_id": binding.enrollment_id,
            "old_idempotency_key": old_idempotency_key,
            "old_nonce": old_nonce,
            "old_expires_at": old_expires_at,
            "enrollment_id": enrollment_id,
            "idempotency_key": idempotency_key,
            "challenge_nonce": nonce,
            "expires_at": expires_at,
            "updated_at": updated_at,
        },
    )
    return bool(result.rowcount)


async def complete_arkade_binding(
    *,
    account_id: str,
    enrollment_id: str,
    idempotency_key: str,
    nonce: str,
    expires_at: datetime,
    server_utc_now: datetime,
    identity_xonly_pubkey: str,
    acknowledged_at: datetime,
    conn: Connection | None = None,
) -> bool:
    database = conn or db
    now = datetime.now(timezone.utc)
    result = await database.execute(
        # Timestamp placeholders are generated by the trusted DB adapter.
        f"""
        UPDATE arkade_account_bindings SET
            state = 'ready',
            identity_xonly_pubkey = :identity_xonly_pubkey,
            backup_acknowledged_at = {
                database.timestamp_placeholder('acknowledged_at')
            },
            ready_at = {database.timestamp_placeholder('ready_at')},
            updated_at = {database.timestamp_placeholder('updated_at')},
            challenge_nonce = NULL,
            challenge_expires_at = NULL
        WHERE account_id = :account_id
          AND state = 'pending'
          AND enrollment_id = :enrollment_id
          AND idempotency_key = :idempotency_key
          AND challenge_nonce = :nonce
          AND challenge_expires_at = {database.timestamp_placeholder('expires_at')}
          AND challenge_expires_at > {database.timestamp_placeholder('server_utc_now')}
        """,  # noqa: S608
        {
            "account_id": account_id,
            "enrollment_id": enrollment_id,
            "idempotency_key": idempotency_key,
            "nonce": nonce,
            "expires_at": expires_at,
            "server_utc_now": server_utc_now,
            "identity_xonly_pubkey": identity_xonly_pubkey,
            "acknowledged_at": acknowledged_at,
            "ready_at": now,
            "updated_at": now,
        },
    )
    return bool(result.rowcount)


async def ensure_arkade_account_deletion_allowed(
    account_id: str, conn: Connection | None = None
) -> None:
    if settings.lnbits_effective_installation_mode == "arkade_noncustodial":
        raise ValueError("ARKADE_ACCOUNT_DELETION_BLOCKED")


async def ensure_arkade_wallet_creation_allowed(
    user_id: str,
    wallet_type: str,
    allow_pending: bool = False,
    conn: Connection | None = None,
) -> None:
    if settings.lnbits_effective_installation_mode != "arkade_noncustodial":
        return
    if wallet_type == "lightning-shared":
        raise ValueError("ARKADE_SHARED_WALLET_UNSUPPORTED")
    binding = await get_arkade_binding(user_id, conn=conn)
    if allow_pending and binding and binding.state == "pending":
        return
    if not binding or binding.state != "ready":
        raise ValueError("ARKADE_ENROLLMENT_REQUIRED")


async def ensure_arkade_wallet_deletion_allowed(
    wallet_id: str, deleted: bool = True, conn: Connection | None = None
) -> None:
    if settings.lnbits_effective_installation_mode != "arkade_noncustodial":
        return
    wallet = await (conn or db).fetchone(
        'SELECT "user", deleted FROM wallets WHERE id = :wallet',
        {"wallet": wallet_id},
    )
    if not wallet:
        return
    binding = await get_arkade_binding(wallet["user"], conn=conn)
    if not binding:
        raise ValueError("ARKADE_WALLET_DELETION_BLOCKED")
    if binding.state != "ready":
        raise ValueError("ARKADE_ENROLLMENT_REQUIRED")
    # Reactivation and removal of an already inactive row cannot remove the
    # final active logical wallet.
    if not deleted or wallet["deleted"]:
        return
    row = await (conn or db).fetchone(
        "SELECT COUNT(*) AS count FROM wallets "
        'WHERE "user" = :user AND deleted = false',
        {"user": wallet["user"]},
    )
    if int(row["count"]) <= 1:
        raise ValueError("ARKADE_FINAL_WALLET_DELETION_BLOCKED")
